//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AncestryDnaClustering.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AncestryUserName {
            get {
                return ((string)(this["AncestryUserName"]));
            }
            set {
                this["AncestryUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedTestId {
            get {
                return ((string)(this["SelectedTestId"]));
            }
            set {
                this["SelectedTestId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumTestsToRetrieve {
            get {
                return ((int)(this["NumTestsToRetrieve"]));
            }
            set {
                this["NumTestsToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HighestSharedMatchToRetrieve {
            get {
                return ((int)(this["HighestSharedMatchToRetrieve"]));
            }
            set {
                this["HighestSharedMatchToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedTabIndex {
            get {
                return ((int)(this["SelectedTabIndex"]));
            }
            set {
                this["SelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinClusterSize {
            get {
                return ((int)(this["MinClusterSize"]));
            }
            set {
                this["MinClusterSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filename {
            get {
                return ((string)(this["Filename"]));
            }
            set {
                this["Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumMatchesToCluster {
            get {
                return ((int)(this["NumMatchesToCluster"]));
            }
            set {
                this["NumMatchesToCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HighestSharedMatchToConsider {
            get {
                return ((int)(this["HighestSharedMatchToConsider"]));
            }
            set {
                this["HighestSharedMatchToConsider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DistanceFilename {
            get {
                return ((string)(this["DistanceFilename"]));
            }
            set {
                this["DistanceFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlattenedFilename {
            get {
                return ((string)(this["FlattenedFilename"]));
            }
            set {
                this["FlattenedFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CorrelationFilename {
            get {
                return ((string)(this["CorrelationFilename"]));
            }
            set {
                this["CorrelationFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterToGuids {
            get {
                return ((string)(this["FilterToGuids"]));
            }
            set {
                this["FilterToGuids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedDownloadOptions {
            get {
                return ((bool)(this["ShowAdvancedDownloadOptions"]));
            }
            set {
                this["ShowAdvancedDownloadOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DownloadTypeFast {
            get {
                return ((bool)(this["DownloadTypeFast"]));
            }
            set {
                this["DownloadTypeFast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadTypeComplete {
            get {
                return ((bool)(this["DownloadTypeComplete"]));
            }
            set {
                this["DownloadTypeComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedClusteringOptions {
            get {
                return ((bool)(this["ShowAdvancedClusteringOptions"]));
            }
            set {
                this["ShowAdvancedClusteringOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClusterTypeVeryClose {
            get {
                return ((bool)(this["ClusterTypeVeryClose"]));
            }
            set {
                this["ClusterTypeVeryClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClusterTypeOver20 {
            get {
                return ((bool)(this["ClusterTypeOver20"]));
            }
            set {
                this["ClusterTypeOver20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClusterTypeComplete {
            get {
                return ((bool)(this["ClusterTypeComplete"]));
            }
            set {
                this["ClusterTypeComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double MinCentimorgansToCluster {
            get {
                return ((double)(this["MinCentimorgansToCluster"]));
            }
            set {
                this["MinCentimorgansToCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double MinCentimorgansInSharedMatches {
            get {
                return ((double)(this["MinCentimorgansInSharedMatches"]));
            }
            set {
                this["MinCentimorgansInSharedMatches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double MaxGrayPercentage {
            get {
                return ((double)(this["MaxGrayPercentage"]));
            }
            set {
                this["MaxGrayPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedDistanceOptions {
            get {
                return ((bool)(this["ShowAdvancedDistanceOptions"]));
            }
            set {
                this["ShowAdvancedDistanceOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilenameDistance {
            get {
                return ((string)(this["FilenameDistance"]));
            }
            set {
                this["FilenameDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinClusterSizeDistance {
            get {
                return ((int)(this["MinClusterSizeDistance"]));
            }
            set {
                this["MinClusterSizeDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double MinCentimorgansToCompareDistance {
            get {
                return ((double)(this["MinCentimorgansToCompareDistance"]));
            }
            set {
                this["MinCentimorgansToCompareDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double MinCentimorgansInSharedMatchesDistance {
            get {
                return ((double)(this["MinCentimorgansInSharedMatchesDistance"]));
            }
            set {
                this["MinCentimorgansInSharedMatchesDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DistanceBasisIds {
            get {
                return ((string)(this["DistanceBasisIds"]));
            }
            set {
                this["DistanceBasisIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MatchesLoaderFilterIndex {
            get {
                return ((int)(this["MatchesLoaderFilterIndex"]));
            }
            set {
                this["MatchesLoaderFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadTypeEndogamy {
            get {
                return ((bool)(this["DownloadTypeEndogamy"]));
            }
            set {
                this["DownloadTypeEndogamy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinCentimorgansToRetrieve {
            get {
                return ((double)(this["MinCentimorgansToRetrieve"]));
            }
            set {
                this["MinCentimorgansToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinSharedMatchesCentimorgansToRetrieve {
            get {
                return ((double)(this["MinSharedMatchesCentimorgansToRetrieve"]));
            }
            set {
                this["MinSharedMatchesCentimorgansToRetrieve"] = value;
            }
        }
    }
}
