//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedClustering.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AncestryUserName {
            get {
                return ((string)(this["AncestryUserName"]));
            }
            set {
                this["AncestryUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedTestId {
            get {
                return ((string)(this["SelectedTestId"]));
            }
            set {
                this["SelectedTestId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumTestsToRetrieve {
            get {
                return ((int)(this["NumTestsToRetrieve"]));
            }
            set {
                this["NumTestsToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HighestSharedMatchToRetrieve {
            get {
                return ((int)(this["HighestSharedMatchToRetrieve"]));
            }
            set {
                this["HighestSharedMatchToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedTabIndex {
            get {
                return ((int)(this["SelectedTabIndex"]));
            }
            set {
                this["SelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinClusterSize {
            get {
                return ((int)(this["MinClusterSize"]));
            }
            set {
                this["MinClusterSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filename {
            get {
                return ((string)(this["Filename"]));
            }
            set {
                this["Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumMatchesToCluster {
            get {
                return ((int)(this["NumMatchesToCluster"]));
            }
            set {
                this["NumMatchesToCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HighestSharedMatchToConsider {
            get {
                return ((int)(this["HighestSharedMatchToConsider"]));
            }
            set {
                this["HighestSharedMatchToConsider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SimilarityFilename {
            get {
                return ((string)(this["SimilarityFilename"]));
            }
            set {
                this["SimilarityFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlattenedFilename {
            get {
                return ((string)(this["FlattenedFilename"]));
            }
            set {
                this["FlattenedFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CorrelationFilename {
            get {
                return ((string)(this["CorrelationFilename"]));
            }
            set {
                this["CorrelationFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterToGuids {
            get {
                return ((string)(this["FilterToGuids"]));
            }
            set {
                this["FilterToGuids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedDownloadOptions {
            get {
                return ((bool)(this["ShowAdvancedDownloadOptions"]));
            }
            set {
                this["ShowAdvancedDownloadOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DownloadTypeFast {
            get {
                return ((bool)(this["DownloadTypeFast"]));
            }
            set {
                this["DownloadTypeFast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadTypeComplete {
            get {
                return ((bool)(this["DownloadTypeComplete"]));
            }
            set {
                this["DownloadTypeComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedClusteringOptions {
            get {
                return ((bool)(this["ShowAdvancedClusteringOptions"]));
            }
            set {
                this["ShowAdvancedClusteringOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClusterTypeClose {
            get {
                return ((bool)(this["ClusterTypeClose"]));
            }
            set {
                this["ClusterTypeClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClusterTypeOver20 {
            get {
                return ((bool)(this["ClusterTypeOver20"]));
            }
            set {
                this["ClusterTypeOver20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClusterTypeComplete {
            get {
                return ((bool)(this["ClusterTypeComplete"]));
            }
            set {
                this["ClusterTypeComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double MinCentimorgansToCluster {
            get {
                return ((double)(this["MinCentimorgansToCluster"]));
            }
            set {
                this["MinCentimorgansToCluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double MinCentimorgansInSharedMatches {
            get {
                return ((double)(this["MinCentimorgansInSharedMatches"]));
            }
            set {
                this["MinCentimorgansInSharedMatches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double MaxGrayPercentage {
            get {
                return ((double)(this["MaxGrayPercentage"]));
            }
            set {
                this["MaxGrayPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAdvancedSimilarityOptions {
            get {
                return ((bool)(this["ShowAdvancedSimilarityOptions"]));
            }
            set {
                this["ShowAdvancedSimilarityOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilenameSimilarity {
            get {
                return ((string)(this["FilenameSimilarity"]));
            }
            set {
                this["FilenameSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinClusterSizeSimilarity {
            get {
                return ((int)(this["MinClusterSizeSimilarity"]));
            }
            set {
                this["MinClusterSizeSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double MinCentimorgansToCompareSimilarity {
            get {
                return ((double)(this["MinCentimorgansToCompareSimilarity"]));
            }
            set {
                this["MinCentimorgansToCompareSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double MinCentimorgansInSharedMatchesSimilarity {
            get {
                return ((double)(this["MinCentimorgansInSharedMatchesSimilarity"]));
            }
            set {
                this["MinCentimorgansInSharedMatchesSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SimilarityBasisIds {
            get {
                return ((string)(this["SimilarityBasisIds"]));
            }
            set {
                this["SimilarityBasisIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MatchesLoaderFilterIndex {
            get {
                return ((int)(this["MatchesLoaderFilterIndex"]));
            }
            set {
                this["MatchesLoaderFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadTypeEndogamy {
            get {
                return ((bool)(this["DownloadTypeEndogamy"]));
            }
            set {
                this["DownloadTypeEndogamy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinCentimorgansToRetrieve {
            get {
                return ((double)(this["MinCentimorgansToRetrieve"]));
            }
            set {
                this["MinCentimorgansToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinSharedMatchesCentimorgansToRetrieve {
            get {
                return ((double)(this["MinSharedMatchesCentimorgansToRetrieve"]));
            }
            set {
                this["MinSharedMatchesCentimorgansToRetrieve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFileDownloaded {
            get {
                return ((string)(this["LastFileDownloaded"]));
            }
            set {
                this["LastFileDownloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenClusterFileWhenComplete {
            get {
                return ((bool)(this["OpenClusterFileWhenComplete"]));
            }
            set {
                this["OpenClusterFileWhenComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenSimilarityFileWhenComplete {
            get {
                return ((bool)(this["OpenSimilarityFileWhenComplete"]));
            }
            set {
                this["OpenSimilarityFileWhenComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.ancestry.com")]
        public string AncestryHostName {
            get {
                return ((string)(this["AncestryHostName"]));
            }
            set {
                this["AncestryHostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MaxMatchesPerClusterFile {
            get {
                return ((int)(this["MaxMatchesPerClusterFile"]));
            }
            set {
                this["MaxMatchesPerClusterFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsedDirectory {
            get {
                return ((string)(this["LastUsedDirectory"]));
            }
            set {
                this["LastUsedDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExcludeClustersGreaterThan {
            get {
                return ((int)(this["ExcludeClustersGreaterThan"]));
            }
            set {
                this["ExcludeClustersGreaterThan"] = value;
            }
        }
    }
}
